//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    public partial class Book : object
    {
        
        private string IdField;
        
        private string TitleField;
        
        private string CategoryField;
        
        private string LangField;
        
        private int PagesField;
        
        private int AgeLimitField;
        
        private int PublicationDateField;
        
        private ServiceReference1.Author[] AuthorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Pages
        {
            get
            {
                return this.PagesField;
            }
            set
            {
                this.PagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int AgeLimit
        {
            get
            {
                return this.AgeLimitField;
            }
            set
            {
                this.AgeLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int PublicationDate
        {
            get
            {
                return this.PublicationDateField;
            }
            set
            {
                this.PublicationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ServiceReference1.Author[] Authors
        {
            get
            {
                return this.AuthorsField;
            }
            set
            {
                this.AuthorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://tempuri.org/")]
    public partial class Author : object
    {
        
        private string NameField;
        
        private string LangField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.LibraryWebServiceSoap")]
    public interface LibraryWebServiceSoap
    {
        
        // CODEGEN: Создание контракта сообщения, так как имя элемента title из пространства имен http://tempuri.org/ не отмечено как обнуляемое.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookByTitle", ReplyAction="*")]
        ServiceReference1.GetBookByTitleResponse GetBookByTitle(ServiceReference1.GetBookByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookByTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetBookByTitleResponse> GetBookByTitleAsync(ServiceReference1.GetBookByTitleRequest request);
        
        // CODEGEN: Создание контракта сообщения, так как имя элемента name из пространства имен http://tempuri.org/ не отмечено как обнуляемое.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookByName", ReplyAction="*")]
        ServiceReference1.GetBookByNameResponse GetBookByName(ServiceReference1.GetBookByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetBookByNameResponse> GetBookByNameAsync(ServiceReference1.GetBookByNameRequest request);
        
        // CODEGEN: Создание контракта сообщения, так как имя элемента category из пространства имен http://tempuri.org/ не отмечено как обнуляемое.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookByCategory", ReplyAction="*")]
        ServiceReference1.GetBookByCategoryResponse GetBookByCategory(ServiceReference1.GetBookByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetBookByCategoryResponse> GetBookByCategoryAsync(ServiceReference1.GetBookByCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByTitleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByTitle", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetBookByTitleRequestBody Body;
        
        public GetBookByTitleRequest()
        {
        }
        
        public GetBookByTitleRequest(ServiceReference1.GetBookByTitleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookByTitleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public GetBookByTitleRequestBody()
        {
        }
        
        public GetBookByTitleRequestBody(string title)
        {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByTitleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetBookByTitleResponseBody Body;
        
        public GetBookByTitleResponse()
        {
        }
        
        public GetBookByTitleResponse(ServiceReference1.GetBookByTitleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookByTitleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Book[] GetBookByTitleResult;
        
        public GetBookByTitleResponseBody()
        {
        }
        
        public GetBookByTitleResponseBody(ServiceReference1.Book[] GetBookByTitleResult)
        {
            this.GetBookByTitleResult = GetBookByTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByName", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetBookByNameRequestBody Body;
        
        public GetBookByNameRequest()
        {
        }
        
        public GetBookByNameRequest(ServiceReference1.GetBookByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookByNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetBookByNameRequestBody()
        {
        }
        
        public GetBookByNameRequestBody(string name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetBookByNameResponseBody Body;
        
        public GetBookByNameResponse()
        {
        }
        
        public GetBookByNameResponse(ServiceReference1.GetBookByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Book[] GetBookByNameResult;
        
        public GetBookByNameResponseBody()
        {
        }
        
        public GetBookByNameResponseBody(ServiceReference1.Book[] GetBookByNameResult)
        {
            this.GetBookByNameResult = GetBookByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByCategory", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetBookByCategoryRequestBody Body;
        
        public GetBookByCategoryRequest()
        {
        }
        
        public GetBookByCategoryRequest(ServiceReference1.GetBookByCategoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookByCategoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        public GetBookByCategoryRequestBody()
        {
        }
        
        public GetBookByCategoryRequestBody(string category)
        {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetBookByCategoryResponseBody Body;
        
        public GetBookByCategoryResponse()
        {
        }
        
        public GetBookByCategoryResponse(ServiceReference1.GetBookByCategoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookByCategoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Book[] GetBookByCategoryResult;
        
        public GetBookByCategoryResponseBody()
        {
        }
        
        public GetBookByCategoryResponseBody(ServiceReference1.Book[] GetBookByCategoryResult)
        {
            this.GetBookByCategoryResult = GetBookByCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface LibraryWebServiceSoapChannel : ServiceReference1.LibraryWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class LibraryWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.LibraryWebServiceSoap>, ServiceReference1.LibraryWebServiceSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LibraryWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LibraryWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), LibraryWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LibraryWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LibraryWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetBookByTitleResponse ServiceReference1.LibraryWebServiceSoap.GetBookByTitle(ServiceReference1.GetBookByTitleRequest request)
        {
            return base.Channel.GetBookByTitle(request);
        }
        
        public ServiceReference1.Book[] GetBookByTitle(string title)
        {
            ServiceReference1.GetBookByTitleRequest inValue = new ServiceReference1.GetBookByTitleRequest();
            inValue.Body = new ServiceReference1.GetBookByTitleRequestBody();
            inValue.Body.title = title;
            ServiceReference1.GetBookByTitleResponse retVal = ((ServiceReference1.LibraryWebServiceSoap)(this)).GetBookByTitle(inValue);
            return retVal.Body.GetBookByTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetBookByTitleResponse> ServiceReference1.LibraryWebServiceSoap.GetBookByTitleAsync(ServiceReference1.GetBookByTitleRequest request)
        {
            return base.Channel.GetBookByTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBookByTitleResponse> GetBookByTitleAsync(string title)
        {
            ServiceReference1.GetBookByTitleRequest inValue = new ServiceReference1.GetBookByTitleRequest();
            inValue.Body = new ServiceReference1.GetBookByTitleRequestBody();
            inValue.Body.title = title;
            return ((ServiceReference1.LibraryWebServiceSoap)(this)).GetBookByTitleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetBookByNameResponse ServiceReference1.LibraryWebServiceSoap.GetBookByName(ServiceReference1.GetBookByNameRequest request)
        {
            return base.Channel.GetBookByName(request);
        }
        
        public ServiceReference1.Book[] GetBookByName(string name)
        {
            ServiceReference1.GetBookByNameRequest inValue = new ServiceReference1.GetBookByNameRequest();
            inValue.Body = new ServiceReference1.GetBookByNameRequestBody();
            inValue.Body.name = name;
            ServiceReference1.GetBookByNameResponse retVal = ((ServiceReference1.LibraryWebServiceSoap)(this)).GetBookByName(inValue);
            return retVal.Body.GetBookByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetBookByNameResponse> ServiceReference1.LibraryWebServiceSoap.GetBookByNameAsync(ServiceReference1.GetBookByNameRequest request)
        {
            return base.Channel.GetBookByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBookByNameResponse> GetBookByNameAsync(string name)
        {
            ServiceReference1.GetBookByNameRequest inValue = new ServiceReference1.GetBookByNameRequest();
            inValue.Body = new ServiceReference1.GetBookByNameRequestBody();
            inValue.Body.name = name;
            return ((ServiceReference1.LibraryWebServiceSoap)(this)).GetBookByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetBookByCategoryResponse ServiceReference1.LibraryWebServiceSoap.GetBookByCategory(ServiceReference1.GetBookByCategoryRequest request)
        {
            return base.Channel.GetBookByCategory(request);
        }
        
        public ServiceReference1.Book[] GetBookByCategory(string category)
        {
            ServiceReference1.GetBookByCategoryRequest inValue = new ServiceReference1.GetBookByCategoryRequest();
            inValue.Body = new ServiceReference1.GetBookByCategoryRequestBody();
            inValue.Body.category = category;
            ServiceReference1.GetBookByCategoryResponse retVal = ((ServiceReference1.LibraryWebServiceSoap)(this)).GetBookByCategory(inValue);
            return retVal.Body.GetBookByCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetBookByCategoryResponse> ServiceReference1.LibraryWebServiceSoap.GetBookByCategoryAsync(ServiceReference1.GetBookByCategoryRequest request)
        {
            return base.Channel.GetBookByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBookByCategoryResponse> GetBookByCategoryAsync(string category)
        {
            ServiceReference1.GetBookByCategoryRequest inValue = new ServiceReference1.GetBookByCategoryRequest();
            inValue.Body = new ServiceReference1.GetBookByCategoryRequestBody();
            inValue.Body.category = category;
            return ((ServiceReference1.LibraryWebServiceSoap)(this)).GetBookByCategoryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61685/LibraryWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61685/LibraryWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LibraryWebServiceSoap,
            
            LibraryWebServiceSoap12,
        }
    }
}
